### ISSUE TITLE
Analisis de Sonar Qube

### ISSUE THREAD

**Issue by JoaquinHC9** [JoaquinHC9/Alfashop2.0#22]
Realizar y problemas detectados en el analisis de SonarQube

**Comment by JoaquinHC9** [comment]
![Captura de pantalla 2024-12-10 172926](https://github.com/user-attachments/assets/27909905-3670-454d-b9fc-e075d830fda8)

**Comment by emersonHO** [comment]
**Documento detallado**

Cobertura más detallada, a través del análisis de SonarQube

[2024-12-07--AlfaShop--back--analysis-report.docx](https://github.com/user-attachments/files/18087999/2024-12-07--AlfaShop--back--analysis-report.docx)

Reporte en formato .cm

[2024-12-07--AlfaShop--back--analysis-report.md](https://github.com/user-attachments/files/18088021/2024-12-07--AlfaShop--back--analysis-report.md)

**Comment by JoaquinHC9** [comment]
# Frontend
 Se limpio la calidad del backend y se aumento la covertura al 80% (fue implementado Jacoco para el reporte de cobertura).
![image](https://github.com/user-attachments/assets/c6c179dc-3ae3-4d18-8b4b-8627149c50ac)
# Backend 
En el frontend se hace uso de cypress io coverage para los reportes funcionales
![image](https://github.com/user-attachments/assets/bf879299-9bdb-4a89-8b60-96a48813ff67)
