### ISSUE TITLE
Configuración y ejecución de pruebas de rendimiento con JMeter

### ISSUE THREAD

**Issue by emersonHO** [JoaquinHC9/Alfashop2.0#23]
Asignado a @GHOPsT 

**Descripción**
Explorar JMeter para realizar pruebas básicas de rendimiento en el sistema.

**Tareas**

- Configurar JMeter en tu entorno local.
- Diseñar un plan de prueba simple para uno o dos endpoints principales.
- Generar un reporte con las métricas clave que encuentres.

**Resultado esperado**
- Un reporte inicial con observaciones sobre el rendimiento.

**Comment by JoaquinHC9** [comment]
Similarmente se añadió el archivo de pruebas alfashopruebas.jmx al repositorio
