### ISSUE TITLE
Pruebas funcionales simples con Cypress

### ISSUE THREAD

**Issue by emersonHO** [JoaquinHC9/Alfashop2.0#25]
Asignado a: @JoaquinHC9 

**Descripción**

Configurar Cypress y realizar pruebas funcionales simples para los flujos principales del frontend.

**Tareas sugeridas**

- Instalar Cypress en el proyecto.
- Crear una o dos pruebas básicas para verificar flujos esenciales (por ejemplo, login o registro).
- Ejecutar las pruebas y guardar los resultados.

**Resultado esperado**

- Pruebas funcionales básicas que validen al menos un flujo principal del frontend.

**Comment by JoaquinHC9** [comment]
Las  pruebas funcionales se pueden ver utilizando el comando 
npm run cypress:open, luego de haber ejecutado npm run dev en otro terminal
![image](https://github.com/user-attachments/assets/878e2158-f32d-4230-b551-f7ba9a3b7f7b)
