### ISSUE TITLE
Ejecutar un escaneo inicial con OWASP ZAP

### ISSUE THREAD

**Issue by emersonHO** [JoaquinHC9/Alfashop2.0#26]
Asignado a: @Noesax

**Descripción**

Probar OWASP ZAP con un escaneo inicial para identificar posibles riesgos de seguridad.

**Tareas sugeridas**

- Configurar OWASP ZAP para conectarlo al proyecto.
- Ejecutar un escaneo rápido en una parte del sistema (API o frontend).
- Documentar brevemente cualquier hallazgo importante.

**Resultado esperado**

- Un reporte básico de OWASP ZAP con observaciones preliminares.

**Comment by JoaquinHC9** [comment]
Esta resulto cuando se añadio el jenkins revisar readme
