### ISSUE TITLE
Configurar y probar SonarQube

### ISSUE THREAD

**Issue by emersonHO** [JoaquinHC9/Alfashop2.0#27]
Asignado a: @Alex9xl 

**Descripción**

Configurar SonarQube en el proyecto y realizar un análisis inicial.

**Tareas sugeridas**

- Instalar y configurar SonarQube (local o en línea).
- Analizar una pequeña parte del código del proyecto.
- Compartir los resultados básicos del análisis.

**Resultado esperado**

- Un análisis inicial con SonarQube y un breve reporte de los hallazgos.

**Comment by Alex9xl** [comment]
# Análisis estático del código con SonarQube
Se realizaron usando Jenkins, la instalación y configuración se detalla en el README.md 

## Reporte de pruebas
Se realizaron pruebas tanto al backend como al frontend.

### Reporte de análisis del Backend
[SonarQube-Analysis-Backend-report.zip](https://github.com/user-attachments/files/18103494/SonarQube-Analysis-Backend-report.zip)


### Reporte de análisis del Frontend
[SonarQube-Analysis-Frontend-report.zip](https://github.com/user-attachments/files/18103496/SonarQube-Analysis-Frontend-report.zip)
