### ISSUE TITLE
Actualizar el README.md con información básica

### ISSUE THREAD

**Issue by emersonHO** [JoaquinHC9/Alfashop2.0#28]
Asignado a: @emersonHO 

Actualizar el README.md para que contenga información mínima y útil sobre el proyecto.

**Tareas sugeridas**

- Incluir una breve descripción del proyecto.
- Agregar instrucciones simples de cómo ejecutar el proyecto localmente.
- Revisar que el formato sea claro y legible.

**Resultado esperado**

- Un README.md más claro con información básica sobre el proyecto.

**Comment by Alex9xl** [comment]
# Análisis estático del código con SonarQube
Se realizaron pruebas usando Jenkins, se actualizo el README.md 

## Reporte de pruebas
Se realizaron pruebas tanto al backend como al frontend

### Reporte de análisis del Backend
[SonarQube-Analysis-Backend-report.zip](https://github.com/user-attachments/files/18103453/SonarQube-Analysis-Backend-report.zip)


### Reporte de análisis del Frontend
[SonarQube-Analysis-Frontend-report.zip](https://github.com/user-attachments/files/18103455/SonarQube-Analysis-Frontend-report.zip)

**Comment by JoaquinHC9** [comment]
Ya se arreglo el readme
